services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/mern-task
      - JWT_SECRET=your-secret-key
      - YARN_CACHE_FOLDER=/usr/src/app/.yarn/cache
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.yarn/cache
      - /usr/src/app/node_modules
    working_dir: /usr/src/app

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
